development:
  adapter: postgresql
  encoding: unicode
  database: new_pal_development
  pool: 5
  username: johnzw89
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: new_pal_test
  pool: 5
  username: johnzw89
  password:

production:
  adapter: postgresql
  database: new_pal_production
  pool: 5
  timeout: 5000
